[project]
name = "mcp-wordle"
version = "0.1.0"
description = "An MCP server implementation of the Wordle game that can be played through AI assistants like Claude."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.4",
]
